import { Component } from '@angular/core';

@Component({
  selector: 'life',
  templateUrl: 'life.html'
})
export class LifeHackPage {

  model: IHack = {
    title: '20 Amazing Kitchen Life-Hacks That Are Absolutely Genius',
    items: [
      { hackName: 'Bake bacon in the oven.', hackImg: '/assets/hack/2.jpg',  hackText: 'Ever wonder why the bacon you get at a restaurant is always evenly and consistently cooked with no annoying raw ends? Ever wonder why the middles don’t get all crumbly or hard and overcooked? The difference is all in the cooking. Whereas most home chefs fry up bacon on the frying pan, most restaurant workers bake it in the oven. Try it out at 400 to 420 degrees Fahrenheit and be amazed!' },
      {hackName:'Slice a lot of cherry tomatoes simultaneously.', hackImg:'/assets/hack/3.jpg', hackText:'Cherry tomatoes add a delicious splash of flavor and color to any dish—but slicing them in half is really difficult if you have to do it one at a time. But you don’t! Not with this handy little kitchen hack. Have two plastic lids that are the same size? Good. Put a bunch of cherry tomatoes on one of the lids (have it so the inner part of the lid is facing up). Now, put the other lid on top to sandwich them inside. Hold the lid down, grab a knife, and cut through all of them at once. Pull off the lid, and all your cherry tomatoes will be sliced neatly and cleanly.'},
      {hackName:'Make an orange candle.', hackImg:'/assets/hack/4.jpg', hackText:'Yes, oranges can be made into candles, and quite simply too. Start by slicing your orange in half. Do not slice through the part where the stem was—that part will become your “wick” inside the orange, so you want to slice perpendicularly to that part. Next, remove the flesh from inside the orange, but be careful not to remove the part that sticks out inside where the stem used to connect. This becomes the “orange wick.” Now, pour a little oil into the orange half. Olive oil works great. Then use a lighter and light the “wick.” You will have an orange half acting as a candle, burning the oil.'},
      {hackName:'Pancake patterning trick.', hackImg:'/assets/hack/5.jpg', hackText:'Drizzling pancake batter into whimsical patterns using an icing dispenser isn’t the only pancake hack in our kitchen cabinet. Another easy one is cookie cutters, the same ones you use to make sugar cookies over the holidays. Simply place them on your frying pan, pour the batter inside the outlines, and watch as your pancakes rise in amazing shapes. Of course, they will largely be shaped like Christmas trees, snowmen, and gingerbread men, but this makes them the perfect holiday breakfast treat!'},
      {hackName:'Soften butter in minutes.', hackImg:'/assets/hack/6.jpg', hackText:'You’re getting ready for a dinner party, and you’re finally getting everything out on the table. You realize then you forgot to pull the butter out of the fridge. You take it out, and of course it’s hard as a rock. But dinner is in two minutes! What do you do? Nobody likes cold butter that is impossible to cut. It turns out there is a perfect solution which allows you to soften your butter without melting it, and it only takes a couple of minutes. This is an easy way to make your dinner guests happy. Just get a small glass and warm it up, then put it over top of the butter. You can heat up the glass by running warm water over it or by putting it in the microwave for a few seconds. The butter under the glass will quickly soften and will be just the right consistency to easily cut and spread. Voila!'},
      {hackName:'Peel an orange with ease.', hackImg:'/assets/hack/7.jpg', hackText:'Laziness is no longer an excuse for not eating your fruit! Oranges are delicious, but let’s face it, peeling them is a pain. But does it have to be? Not if you use this orange-peeling hack from Jewelpie.com. Put your orange down on a cutting board. Use a knife to slice off a thin bit from the end, and then do the same thing with the end opposite. Next, cut a perpendicular line. You want to go almost clean through the orange, but not all the way. Then you can pull both ends away from each other and stretch out the orange in a long strip. Then you can just grab each slice off the strip and enjoy!'},
      {hackName:'Peel a head of garlic in seconds.', hackImg:'/assets/hack/8.jpg', hackText:'It turns out there is a hack for peeling garlic that is every bit as simple as the hack for shucking corn. All you need is two bowls that are the same size. Put your head of garlic in one of the bowls, and then put the other bowl on top of it to create a closed container. Then simply shake the bowls really hard. In a minute or less, you can open the container back up and look inside. Assuming you shook it hard enough and long enough, you should see all the skins separated from the garlic cloves. Awesome!'},
      {hackName:'Keep brown sugar soft.', hackImg:'/assets/hack/9.jpg', hackText:'And what if your brown sugar is already as hard as a brick? It turns out this is also easy to deal with. Just put it in a baking dish, cover it with a wet paper towel, and throw it in the microwave for twenty seconds. Ta-da! Soft sugar. Don’t have a microwave? You can do it in the oven; it takes five minutes. Just use the bread trick though and this won’t happen anymore.'},
      {hackName:'Replace ice cubes with frozen fruit in drinks.', hackImg:'/assets/hack/10.jpg', hackText:'Serving up some drinks with your meal? Instead of adding ice, think about adding frozen strawberries or grapes or other fruit pieces. They will subtly change the flavor of the drink, so it may take some experimenting to figure out what you like. A lot of people enjoy frozen grapes in white wine for example. Why is this an awesome idea? Frozen fruit cools down your drink without watering it down, and at the end, you can eat the fruit.'},
      {hackName:'Use dental floss to cut cakes and more.', hackImg:'/assets/hack/11.jpg', hackText:'Earlier we talked about using a warm knife to cut cake perfectly. Another easy alternative is a piece of dental floss. Get the unscented type so you won’t mess up the flavor. The floss will make a nice clean cut, and can be used for cakes, pastries, and more. You can use it for soft cheeses too.'},
      {hackName:'How to tell if an avocado is too ripe.', hackImg:'/assets/hack/12.jpg', hackText:'While you are shopping for avocados, how do you know whether an avocado is too ripe or just right? If you sneakily pop off the stem, you can look at the color underneath. An avocado that is too ripe will be brown under the stem, and will be useless to just about everyone. An avocado that is just right will be green underneath the stem. Be sure you are looking at relatively dark avocados to begin with (the lighter green ones are under-ripe). This can help prevent you from wasting money at the grocery store.'},
      {hackName:'Naturally flavored water', hackImg:'/assets/hack/13.jpg', hackText:'Don’t like the taste of pure water? No need to feel ashamed—a lot of people don’t. You shouldn’t let that stop you from staying hydrated, though, especially during the hot summer months. That doesn’t mean you have to go out and buy “flavored water” drinks from the store that are loaded with sugar and weird additives you’ve never heard of! There is a healthier, more delicious way to enjoy water! You can make flavored water really easily! Just get your favorite fresh fruit and put it in a jar with ice and water. The fruit flavor will diffuse into the water. You can also stir in herbs for extra flavor. It’s like fruit juice, but less expensive, with all the hydrating goodness of water and less sugar. You can eat the fruit when you’re done too. Have fun coming up with recipes for flavored water—it’s like mixing sangria (minus the alcohol of course). There are endless flavor possibilities.'},
      {hackName:'Cook a pancake in a rice cooker.', hackImg:'/assets/hack/14.jpg', hackText:'Love pancakes but hate standing over the stove minding them? Pancakes are delicious, but they are time consuming to prepare the traditional way. If you have a rice cooker though, you can skip all that fussing over the stove. Yep—a rice cooker is a multipurpose device. You can pour pancake batter inside and watch in amazement as one giant pancake rises inside.'},
      {hackName:'Check if eggs are fresh or rotten.', hackImg:'/assets/hack/15.jpg', hackText:'There are times you don’t feel like you can rely on the “use by” date for eggs. If you are in doubt, one easy way to check whether an egg is fresh or not is to put it in a large bowl of water. If it sinks and rests on its side at the bottom of the bowl, you can rest assured the egg is fresh and safe to eat. If it is on the bottom but upright, it is on its last legs. Eat it ASAP, and consider hard boiling it just to be on the safe side. If it floats, get rid of it, it’s done.'},
      {hackName:'Make a perfect egg burger.', hackImg:'/assets/hack/16.jpg', hackText:'If you enjoy a burger with an egg on top, the only thing better is a burger with an egg inside. It keeps everything neat and takes time and hassle out of your cooking. How do you do it? Get your burger patty ready, and then set a glass on top of it, face-down. Use the glass to stamp a hole out of the middle of the patty. Put that meat aside. Now, put the burger patty with the hole in it in your frying pan. Start cooking the burger, and then pour an egg into the middle. Watch in wonder as both the burger and egg cook simultaneously, with the egg perfectly contained in the center. You can use the leftover bits of meat from the centers of your patties to make another burger. Scoop your egg-burger off the frying pan, top it with whatever you want, and serve.'},
      {hackName:'Another way to soften butter.', hackImg:'/assets/hack/17.jpg', hackText:'We already talked about heating up a cup and placing it over hard butter to soften it. Here’s another cool trick that works just as well. Have three toothpicks handy? Spear your hard piece of butter to create a tripod that the butter can stand on (a tripod is a stable structure, which is why you are using three toothpicks). Put the tripod in your microwave with the butter on it on a plate. Turn on the microwave and watch the butter. When it gets sufficiently soft, the tripod will collapse—before the butter starts to melt. Pull it out of the microwave, cause it’s done!'},
      {hackName:'Pit cherries the easy way.', hackImg:'/assets/hack/18.jpg', hackText:'Here’s a genius way to save yourself a lot of hassle! Get a soda bottle or a beer bottle, and set a cherry on top of it (with the bottle open). Grab a chopstick, and simply poke down through the top of the cherry and into the bottle. The chopstick will push the pit right out through the bottom of the cherry, and it will pop into the bottle! You can pit a ton of cherries this way really fast, and the bottle conveniently catches all the pits so you can dispose of them all at once with no mess.'},
      {hackName:'Make incredible cheese bread.', hackImg:'/assets/hack/19.jpg', hackText:'Get a loaf of bread and a knife. Make a series of long parallel cuts that go almost clean through, but not quite. You want your bread to stay in a loaf. Next, make a lot of perpendicular cuts to those so you have a cross-hatch pattern. Again, cut deep, but not to the bottom. Now you can grab some slices of cheese and stuff them through the cuts, filling up the crosshatch. Bake or microwave, and the cheese will melt. Top it off with whatever you want, and enjoy!'},
      {hackName:'Freeze leftover vegetable juice and broth.', hackImg:'/assets/hack/20.jpg', hackText:'One thing that professional restaurant workers learn quickly on the job is the importance of not wasting food. How many times do you dice up tomatoes and pour the excess juice down the drain? Here’s a handy trick—freeze it instead. Get an ice cube tray and pour in excess juice from fruits and vegetables. You can also freeze leftover broth this way instead of letting it go to waste. When you need some extra fruit or vegetable juice or broth for a soup or stew, you will have it handy! Never forget that there is almost nothing that you can’t freeze. Have leftover vegetable bits? Even parts like onion stem ends and carrot tops are useful. They are great for flavoring soups.'},
    ]
  }

  constructor() { }
}

interface IHack {
  title: string;
  items: IItem[]
}
interface IItem {
  hackName: string;
  hackText: string;
  hackImg: string;
  
}